"""Generate the Tailwind source file for daisyUI classes used by the package."""

from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import cast

from django.core.management.base import BaseCommand, CommandError, CommandParser

from daisy_forms.classes import all_classes


def generated_css() -> str:
    try:
        package_version = version("django-daisy-forms")
    except PackageNotFoundError:
        package_version = "unknown"
    classes = " ".join(sorted(all_classes()))
    return (
        f"/* Generated by django-daisy-forms {package_version}. */\n"
        f'@source inline("{classes}");\n'
    )


class Command(BaseCommand):
    help = "Generate the Tailwind @source file for django-daisy-forms."

    def add_arguments(self, parser: CommandParser) -> None:
        parser.add_argument("--output", type=Path, default=Path("daisy-forms.css"))
        parser.add_argument("--check", action="store_true")
        parser.add_argument("--print-source-path", action="store_true")

    def handle(self, *args: object, **options: object) -> None:
        if cast(bool, options["print_source_path"]):
            source_path = Path(__file__).parents[2] / "templates"
            self.stdout.write(f'@source "{source_path.resolve()}";')
            return

        output = cast(Path, options["output"])
        contents = generated_css()
        if cast(bool, options["check"]):
            if not output.is_file() or output.read_text() != contents:
                raise CommandError(f"{output} is out of date.")
            return

        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(contents)
